server:
  port: 8764
spring:
  application:
    name: service-feign #服务中心注册名
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/ #服务中心地址
feign:
  hystrix:
    enabled: true #开启熔断

#Feign 的调用，总共分为两层，即 Ribbon 的调用和 Hystrix（熔断处理） 的调用，高版本的 Hystrix 默认是关闭的。
ribbon:
  # 连接超时
  ConnectTimeout: 2000
  # 响应超时
  ReadTimeout: 10000
hystrix:
  threadpool:
    default:
      coreSize: 10 #线程池核心线程数(最大并发数)
  command:
    default:  #这里配default全局有效，配service id指定应用有效
      execution:
        timeout:
          #如果enabled设置为false，则请求超时交给ribbon控制,为true,则超时作为熔断根据
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 3000 #断路器超时时间，默认1000ms


